#!/usr/bin/env python3
"""Export deploy/aisstream/accepted_names.json from fish-report trips + config."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from config import DATA_RAW, MMSI_ALLOWLIST, MMSI_TO_REPORT_BOAT  # noqa: E402
from extract_ais import build_accepted_names  # noqa: E402

OUT = ROOT / "deploy" / "aisstream" / "accepted_names.json"


def main() -> None:
    accepted = build_accepted_names(DATA_RAW / "fish_reports" / "by_year")
    payload = {
        "description": (
            "Normalized AIS vessel name -> socalfishreports boat_name. "
            "Regenerated by scripts/export_accepted_names.py"
        ),
        "n_names": len(accepted),
        "accepted_names": dict(sorted(accepted.items())),
        "mmsi_to_report_boat": {
            str(k): v for k, v in sorted(MMSI_TO_REPORT_BOAT.items())
        },
        "mmsi_allowlist": sorted(MMSI_ALLOWLIST),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {len(accepted)} names -> {OUT}")


if __name__ == "__main__":
    main()
